FROM ubuntu

#RUN apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
#	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

RUN apt-get -y update && \
    apt-get install -y gcc && \
    apt-get install -y make &&\
    apt install -y software-properties-common &&\
    add-apt-repository ppa:deadsnakes/ppa &&\
    apt-get install -y python3-pip &&\
    pip install Flask

RUN pip install pyopenssl

RUN pip install argparse

ENTRYPOINT ["/bin/sh","/bash.sh"]