FROM ubuntu



# Install the dhcpd server.
RUN  apt-get -y update && \ 
     apt-get install -y gcc && \
     apt-get install -y make && \
     apt-get install -y bsdmainutils

RUN apt-get install -y libcurl4-openssl-dev &&\
    apt install -y libb64-dev

RUN apt-get install -y libjson-c-dev
#EXPOSE 53/udp
ENTRYPOINT ["/bin/sh","/bash.sh"]