FROM ubuntu

#RUN apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
#	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8


# Install the dhcpd server.
RUN  apt-get update -y &&\
     apt-get upgrade -y &&\
     apt install -y gcc &&\
     apt install make


ENTRYPOINT ["/bin/sh","/bash.sh"]